// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nation-view/PWStyle.tsx": () => import("../components/mockups/nation-view/PWStyle.tsx")
};
